//pub mod matrix_operations;
pub mod phfibre;
pub mod utilities;
pub mod intervals_and_ordinals;
pub mod rank_calculations;
pub mod polytope;
pub mod permutation_test;
pub mod facet_pipeline;
// pub mod cross_check;
// pub mod facets;